edited the yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,37 +4,37 @@ on:
   push:
     schedule: 
       - cron: "0 */2 * * *"
-      workflow_dispatch:
-      permissions:
-        contents: write
-      jobs:
-        test_and_fetch:
-          runs_on: ubuntu-latest
-          steps:
-          - name: Checkout repo
-            uses: actions/checkout@v4
-          - name: Use node.JS
-            uses: actions/checkout@v4
-            with:
-              node-version: "22"
-          - name: Cache Node modules
-            uses: actions/cache@v3
-            with:
-              path: ~/.npm
-              key: ${{runner.os}}-node-${{hashFiles('package-lock.json')}}
-          - name: Install Dependecies
-            run: npm ci
-          - name: Fetch Latest Weather
-            env:
-              WEATHER_API_KEY: ${{secrets.WEATHER_API_KEY}}
-              WEATHER_CITY: ${{secrets.CITY}}
-            run: node fetchWeather.js
-          - name: Commit weatger data if changd
-            run: |
-              git config user.name "github-actions[bot]"
-              git config user.email "github-actions[bot]@users.noreply.github.com"
-              git add data/weather.jso dataweather_log.csv || true
-              git commit -m "ci: update weather data" || echo "No changes to commit"
-              git push || echo "Push failed or no changes"
-          - name: Trigger Render 
-            run: curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}
+    workflow_dispatch:
+permissions:
+  contents: write
+jobs:
+  test_and_fetch:
+    runs_on: ubuntu-latest
+    steps:
+    - name: Checkout repo
+      uses: actions/checkout@v4
+    - name: Use node.JS
+      uses: actions/checkout@v4
+      with:
+        node-version: "22"
+    - name: Cache Node modules
+      uses: actions/cache@v3
+      with:
+        path: ~/.npm
+        key: ${{runner.os}}-node-${{hashFiles('package-lock.json')}}
+    - name: Install Dependecies
+      run: npm ci
+    - name: Fetch Latest Weather
+      env:
+        WEATHER_API_KEY: ${{secrets.WEATHER_API_KEY}}
+        WEATHER_CITY: ${{secrets.CITY}}
+      run: node fetchWeather.js
+    - name: Commit weatger data if changd
+      run: |
+        git config user.name "github-actions[bot]"
+        git config user.email "github-actions[bot]@users.noreply.github.com"
+        git add data/weather.jso dataweather_log.csv || true
+        git commit -m "ci: update weather data" || echo "No changes to commit"
+        git push || echo "Push failed or no changes"
+    - name: Trigger Render 
+      run: curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}
